language: node_js
node_js:
  - "7"
addons:
    code_climate: 
        repo_token: 
          secure: 69280dbeef9a1325a4d78c6d310995fdea180b42141ebecc7ed50390a433306c
env:
global:
- export NODE_ENV=test  
before_script:
- npm install
- npm install codeclimate-test-reporter istanbul -g
script:
- npm test
after_script:
  - codeclimate-test-reporter < ./coverage/Icov.info
notifications:
  email: false 

